# Generated by Django on 2026-09-14
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(help_text='Unique Registration Number of the student (e.g. 717621CS001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full Name of the student', max_length=100)),
                ('email', models.EmailField(help_text='Unique official or personal email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact telephone number', max_length=20)),
                ('department', models.CharField(help_text='Academic Department (e.g. Computer Science and Engineering)', max_length=100)),
                ('year', models.PositiveSmallIntegerField(help_text='Current Year of study (1 to 4/5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('section', models.CharField(help_text='Section (e.g. A, B, C)', max_length=10)),
                ('admission_date', models.DateField(blank=True, help_text='Date of admission into the college (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'attendance_student',
                'ordering': ['register_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Unique Subject Code (e.g. CS8491)', max_length=20, unique=True)),
                ('subject_name', models.CharField(help_text='Name of the course/subject', max_length=150)),
                ('department', models.CharField(help_text='Department offering this subject', max_length=100)),
                ('year', models.PositiveSmallIntegerField(help_text='Academic Year (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('semester', models.PositiveSmallIntegerField(help_text='Academic Semester (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'attendance_subject',
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(help_text='Date when attendance was taken')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', help_text='Attendance status: Present or Absent', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text='Optional remarks or notes regarding attendance', max_length=255, null=True)),
                ('student', models.ForeignKey(help_text='Foreign Key referencing Student table', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
                ('subject', models.ForeignKey(help_text='Foreign Key referencing Subject table', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.subject')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_record',
                'ordering': ['-attendance_date', 'student__register_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'attendance_date'), name='unique_student_subject_attendance_date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Present', 'Absent'])), name='valid_attendance_status'),
        ),
    ]
